#!/bin/bash
cmsRun fitMuonTrigger_B.py
cmsRun fitMuonTrigger_C.py
cmsRun fitMuonTrigger_D.py
cmsRun fitMuonTrigger_E.py
cmsRun fitMuonTrigger_F.py
cmsRun fitMuonTrigger_G.py
cmsRun fitMuonTrigger_H.py
cmsRun fitMuonTrigger_MC.py
